<?php
return array (
  '89617ff6f297de41059791787c54d403' => 
  array (
    'author' => 'Marcel Proust',
    'cover_ext' => '',
    'created' => '2017-05-06 16:36:07',
    'date' => '2004-07-15',
    'deleted' => NULL,
    'description' => NULL,
    'identifier' => 'http://www.gutenberg.org/ebooks/8946',
    'language' => 'fr',
    'name' => 'Le Cote de Guermantes - Premiere partie_Marcel Proust_1.epub',
    'number' => 1,
    'publisher' => NULL,
    'rights' => 'Public domain in the USA.',
    'source' => 'pg8946.epub',
    'subject' => 'Autobiographical fiction',
    'title' => 'Le Côté de Guermantes - Première partie',
    'updated' => NULL,
  ),
  '473fd39826f72898833c82d41181a1cb' => 
  array (
    'author' => 'Ken Follett',
    'cover_ext' => 'jpg',
    'created' => '2017-05-06 16:36:48',
    'date' => '2015-05-28',
    'deleted' => NULL,
    'description' => NULL,
    'identifier' => 'urn:uuid:5f67a883-7a53-4771-bd59-c019733411e1',
    'language' => 'en-US',
    'name' => 'Eye of the Needle_Ken Follett_2.epub',
    'number' => 2,
    'publisher' => 'Penguin Publishing Group',
    'rights' => NULL,
    'source' => 'Eye of the Needle - Ken Follett.epub',
    'subject' => NULL,
    'title' => 'Eye of the Needle',
    'updated' => '2017-05-13 16:43:46',
  ),
  '7877d10803326122274737e98d830bbb' => 
  array (
    'author' => 'Douglas Adams',
    'cover_ext' => 'jpg',
    'created' => '2017-05-06 16:36:59',
    'date' => NULL,
    'deleted' => NULL,
    'description' => NULL,
    'identifier' => NULL,
    'language' => 'en-GB',
    'name' => 'The Hitchhiker s Guide to the Galaxy_Douglas Adams_3.epub',
    'number' => 3,
    'publisher' => 'Pan Books',
    'rights' => 'Copyright © Serious Productions Ltd 1979',
    'source' => 'The Hitchhiker\'s Guide to the G - Douglas Adams.epub',
    'subject' => NULL,
    'title' => 'The Hitchhiker’s Guide to the Galaxy',
    'updated' => NULL,
  ),
);
